import type { RunnerTask } from './types'

const toBullets = (items: readonly string[]): string => items.map((i) => `- ${i}`).join('\n')

export const formatRunnerTaskMarkdown = (task: RunnerTask): string => {
  return [
    `Task ID: ${task.id}`,
    `Title: ${task.title}`,
    '',
    'Goal:',
    task.goal,
    '',
    'Constraints:',
    toBullets(task.constraints),
    '',
    'Success criteria:',
    toBullets(task.successCriteria),
    '',
    'Files likely affected:',
    toBullets(task.filesLikelyAffected),
    '',
    `Risk level: ${task.riskLevel}`,
  ].join('\n')
}

export const createBuilderPrompt = (task: RunnerTask): string => {
  return [
    'You are Agent 1: Builder.',
    '',
    'Your job is to implement the requested task using simple, functional, production-grade TypeScript.',
    '',
    'You must:',
    '- prefer pure functions',
    '- prefer explicit inputs and outputs',
    '- avoid hidden global state',
    '- avoid large classes unless there is a clear reason',
    '- keep modules small',
    '- add tests for all important behavior',
    '- preserve deterministic output',
    '- avoid leaking secrets',
    '- optimize for local-first usage',
    '- keep output readable',
    '- use dependency injection where it improves testability',
    '- avoid premature abstraction',
    '',
    'Before making a meaningful change, produce a Decision Record:',
    '',
    'Decision:',
    'Reason:',
    'Files affected:',
    'Alternatives considered:',
    'Risks:',
    'Expected effect on performance:',
    'Expected effect on token usage:',
    'Expected effect on usability:',
    'Expected effect on readability:',
    'Expected effect on security:',
    '',
    'Then wait for Agent 2 evaluation or simulate Agent 2 using the evaluator rubric.',
    '',
    'Current task:',
    '```text',
    formatRunnerTaskMarkdown(task),
    '```',
  ].join('\n')
}

export const createEvaluatorPrompt = (task: RunnerTask): string => {
  return [
    'You are Agent 2: Evaluator.',
    '',
    'Your job is to review every Builder decision and implementation.',
    '',
    'You must score the work from 0 to 5 across:',
    '- performance',
    '- tokenUsage',
    '- usability',
    '- readability',
    '- security',
    '- simplicity',
    '- maintainability',
    '',
    'Scoring rules:',
    '- Any score below 3 fails',
    '- Average below 4 requires revision',
    '- Security below 4 requires mandatory revision',
    '- Token usage below 4 requires mandatory revision',
    '- Performance below 4 requires revision for scanner/cache/build/sync/CLI work',
    '',
    'You must:',
    '- identify risks clearly',
    '- block unsafe changes',
    '- block needless complexity',
    '- block non-deterministic output',
    '- block secret exposure',
    '- block excessive dependencies',
    '- prefer actionable fixes over general feedback',
    '- explain exactly what must change to pass',
    '',
    'Return review output in this format:',
    '',
    'Status: PASS | REVISE | FAIL',
    'Scores:',
    '- performance: N/5',
    '- tokenUsage: N/5',
    '- usability: N/5',
    '- readability: N/5',
    '- security: N/5',
    '- simplicity: N/5',
    '- maintainability: N/5',
    'Average: N.N/5',
    'Blocking issues:',
    '- ...',
    'Required changes:',
    '- ...',
    'Approved next step:',
    '- ...',
    '',
    'Current task:',
    '```text',
    formatRunnerTaskMarkdown(task),
    '```',
  ].join('\n')
}

export const createCopilotDualAgentRunPrompt = (task: RunnerTask): string => {
  return [
    'You are running a dual-agent implementation process for this repository.',
    '',
    'Use two roles:',
    '',
    'Agent 1: Builder',
    '- Implements changes.',
    '- Uses simple functional TypeScript.',
    '- Writes tests.',
    '- Keeps output deterministic, local-first, secure, and performant.',
    '',
    'Agent 2: Evaluator',
    '- Reviews every meaningful decision.',
    '- Scores performance, tokenUsage, usability, readability, security, simplicity, and maintainability from 0 to 5.',
    '- Blocks unsafe, slow, unclear, or over-engineered choices.',
    '',
    'Process:',
    '1. Restate the task.',
    '2. Break it into small implementation steps.',
    '3. For each step, Agent 1 must produce a Decision Record.',
    '4. Agent 2 must score the decision.',
    '5. If the score passes, Agent 1 implements.',
    '6. Agent 2 reviews the implementation.',
    '7. If it fails, revise before moving on.',
    '8. End with a final report of files changed, tests added, risks, and next steps.',
    '',
    'Scoring rules:',
    '- Any score below 3 fails.',
    '- Average below 4 requires revision.',
    '- Security below 4 requires revision.',
    '- Token usage below 4 requires revision.',
    '',
    'Current task:',
    '```text',
    formatRunnerTaskMarkdown(task),
    '```',
  ].join('\n')
}
